import { createHash } from "node:crypto";

/**
 * The tamper-evident audit log is an append-only hash chain (DECISIONS.md, §8):
 *
 *     hash = sha256(prevHash || canonical(row))
 *
 * Each entry commits to the entry before it, so altering, reordering, or dropping
 * any historical row breaks every hash downstream — detectable by `verifyChain`.
 *
 * The functions here are pure and database-free so they can be unit-tested in
 * isolation and reused verbatim by both the writer (compute the next hash) and
 * the verifier (recompute and compare). `seq` is intentionally NOT part of the
 * hash: the row is INSERT-only (UPDATE is blocked by trigger), so the DB-assigned
 * `seq` is unknown at hash time. Chain *order* is carried by the prevHash linkage,
 * not by `seq`.
 */

/** The semantic content of an audit entry that the hash commits to. */
export interface CanonicalAuditRow {
  orgId: string;
  action: string;
  actorType: string;
  actorId: string | null;
  targetType: string;
  targetId: string | null;
  metadata: unknown;
  /** ISO-8601 timestamp, generated by the writer and stored verbatim. */
  createdAt: string;
}

/**
 * Deterministic JSON serialization: object keys are emitted in sorted order at
 * every depth, so two semantically-equal values always produce identical bytes
 * regardless of key insertion order. Arrays keep their order (it is meaningful).
 */
export function canonicalize(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value) ?? "null";
  }
  if (Array.isArray(value)) {
    return `[${value.map(canonicalize).join(",")}]`;
  }
  const entries = Object.keys(value as Record<string, unknown>)
    .sort()
    .map((key) => {
      const v = (value as Record<string, unknown>)[key];
      // Drop undefined so it round-trips identically after a DB read (JSON has no undefined).
      if (v === undefined) return null;
      return `${JSON.stringify(key)}:${canonicalize(v)}`;
    })
    .filter((e): e is string => e !== null);
  return `{${entries.join(",")}}`;
}

/**
 * Compute an entry's hash from the previous entry's hash and the canonical row.
 * The genesis entry has `prevHash === null`, treated as the empty string.
 */
export function computeEntryHash(prevHash: string | null, row: CanonicalAuditRow): string {
  return createHash("sha256")
    .update(prevHash ?? "")
    .update(canonicalize(row))
    .digest("hex");
}

/** A stored entry as read back from the database, in `seq` order. */
export interface StoredAuditEntry extends CanonicalAuditRow {
  seq: bigint;
  prevHash: string | null;
  hash: string;
}

export type VerifyResult =
  | { ok: true; count: number }
  | { ok: false; count: number; brokenAtSeq: bigint; reason: string };

/**
 * Walk a chain in `seq` order and confirm every link:
 *   1. `prevHash` equals the prior entry's `hash` (null for the genesis entry), and
 *   2. `hash` equals `sha256(prevHash || canonical(row))`.
 * Returns the first break found, or ok for a fully intact (or empty) chain.
 */
export function verifyChain(entries: StoredAuditEntry[]): VerifyResult {
  let expectedPrev: string | null = null;
  for (const entry of entries) {
    if (entry.prevHash !== expectedPrev) {
      return {
        ok: false,
        count: entries.length,
        brokenAtSeq: entry.seq,
        reason: `prevHash mismatch: expected ${expectedPrev ?? "null"}, found ${entry.prevHash ?? "null"}`,
      };
    }
    const recomputed = computeEntryHash(entry.prevHash, {
      orgId: entry.orgId,
      action: entry.action,
      actorType: entry.actorType,
      actorId: entry.actorId,
      targetType: entry.targetType,
      targetId: entry.targetId,
      metadata: entry.metadata,
      createdAt: entry.createdAt,
    });
    if (recomputed !== entry.hash) {
      return {
        ok: false,
        count: entries.length,
        brokenAtSeq: entry.seq,
        reason: `hash mismatch: stored ${entry.hash}, recomputed ${recomputed}`,
      };
    }
    expectedPrev = entry.hash;
  }
  return { ok: true, count: entries.length };
}
